# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.14

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /snap/clion/73/bin/cmake/linux/bin/cmake

# The command to remove a file.
RM = /snap/clion/73/bin/cmake/linux/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/rajatha/CLionProjects/SG-1-Memory-Pooling

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/rajatha/CLionProjects/SG-1-Memory-Pooling

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/snap/clion/73/bin/cmake/linux/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/snap/clion/73/bin/cmake/linux/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/snap/clion/73/bin/cmake/linux/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/snap/clion/73/bin/cmake/linux/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/snap/clion/73/bin/cmake/linux/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test

.PHONY : test/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/snap/clion/73/bin/cmake/linux/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/snap/clion/73/bin/cmake/linux/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/snap/clion/73/bin/cmake/linux/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/snap/clion/73/bin/cmake/linux/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/rajatha/CLionProjects/SG-1-Memory-Pooling/CMakeFiles /home/rajatha/CLionProjects/SG-1-Memory-Pooling/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/rajatha/CLionProjects/SG-1-Memory-Pooling/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named carbon

# Build rule for target.
carbon: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 carbon
.PHONY : carbon

# fast build rule for target.
carbon/fast:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/build
.PHONY : carbon/fast

#=============================================================================
# Target rules for targets named carbon-tool

# Build rule for target.
carbon-tool: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 carbon-tool
.PHONY : carbon-tool

# fast build rule for target.
carbon-tool/fast:
	$(MAKE) -f tools/carbon/CMakeFiles/carbon-tool.dir/build.make tools/carbon/CMakeFiles/carbon-tool.dir/build
.PHONY : carbon-tool/fast

#=============================================================================
# Target rules for targets named benches

# Build rule for target.
benches: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 benches
.PHONY : benches

# fast build rule for target.
benches/fast:
	$(MAKE) -f benches/CMakeFiles/benches.dir/build.make benches/CMakeFiles/benches.dir/build
.PHONY : benches/fast

#=============================================================================
# Target rules for targets named bench-mem-pools

# Build rule for target.
bench-mem-pools: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bench-mem-pools
.PHONY : bench-mem-pools

# fast build rule for target.
bench-mem-pools/fast:
	$(MAKE) -f benches/CMakeFiles/bench-mem-pools.dir/build.make benches/CMakeFiles/bench-mem-pools.dir/build
.PHONY : bench-mem-pools/fast

#=============================================================================
# Target rules for targets named examples-error

# Build rule for target.
examples-error: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 examples-error
.PHONY : examples-error

# fast build rule for target.
examples-error/fast:
	$(MAKE) -f examples/CMakeFiles/examples-error.dir/build.make examples/CMakeFiles/examples-error.dir/build
.PHONY : examples-error/fast

#=============================================================================
# Target rules for targets named test-histogram

# Build rule for target.
test-histogram: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test-histogram
.PHONY : test-histogram

# fast build rule for target.
test-histogram/fast:
	$(MAKE) -f tests/CMakeFiles/test-histogram.dir/build.make tests/CMakeFiles/test-histogram.dir/build
.PHONY : test-histogram/fast

#=============================================================================
# Target rules for targets named test-archive-converter

# Build rule for target.
test-archive-converter: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test-archive-converter
.PHONY : test-archive-converter

# fast build rule for target.
test-archive-converter/fast:
	$(MAKE) -f tests/CMakeFiles/test-archive-converter.dir/build.make tests/CMakeFiles/test-archive-converter.dir/build
.PHONY : test-archive-converter/fast

#=============================================================================
# Target rules for targets named test-object-ids

# Build rule for target.
test-object-ids: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test-object-ids
.PHONY : test-object-ids

# fast build rule for target.
test-object-ids/fast:
	$(MAKE) -f tests/CMakeFiles/test-object-ids.dir/build.make tests/CMakeFiles/test-object-ids.dir/build
.PHONY : test-object-ids/fast

#=============================================================================
# Target rules for targets named test-fix-map

# Build rule for target.
test-fix-map: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test-fix-map
.PHONY : test-fix-map

# fast build rule for target.
test-fix-map/fast:
	$(MAKE) -f tests/CMakeFiles/test-fix-map.dir/build.make tests/CMakeFiles/test-fix-map.dir/build
.PHONY : test-fix-map/fast

#=============================================================================
# Target rules for targets named test-archive-ops

# Build rule for target.
test-archive-ops: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test-archive-ops
.PHONY : test-archive-ops

# fast build rule for target.
test-archive-ops/fast:
	$(MAKE) -f tests/CMakeFiles/test-archive-ops.dir/build.make tests/CMakeFiles/test-archive-ops.dir/build
.PHONY : test-archive-ops/fast

#=============================================================================
# Target rules for targets named test-archive-iter

# Build rule for target.
test-archive-iter: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test-archive-iter
.PHONY : test-archive-iter

# fast build rule for target.
test-archive-iter/fast:
	$(MAKE) -f tests/CMakeFiles/test-archive-iter.dir/build.make tests/CMakeFiles/test-archive-iter.dir/build
.PHONY : test-archive-iter/fast

#=============================================================================
# Target rules for targets named test-mempools

# Build rule for target.
test-mempools: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test-mempools
.PHONY : test-mempools

# fast build rule for target.
test-mempools/fast:
	$(MAKE) -f tests/CMakeFiles/test-mempools.dir/build.make tests/CMakeFiles/test-mempools.dir/build
.PHONY : test-mempools/fast

#=============================================================================
# Target rules for targets named test-tagged-ptr

# Build rule for target.
test-tagged-ptr: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test-tagged-ptr
.PHONY : test-tagged-ptr

# fast build rule for target.
test-tagged-ptr/fast:
	$(MAKE) -f tests/CMakeFiles/test-tagged-ptr.dir/build.make tests/CMakeFiles/test-tagged-ptr.dir/build
.PHONY : test-tagged-ptr/fast

#=============================================================================
# Target rules for targets named test-data-ptr

# Build rule for target.
test-data-ptr: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test-data-ptr
.PHONY : test-data-ptr

# fast build rule for target.
test-data-ptr/fast:
	$(MAKE) -f tests/CMakeFiles/test-data-ptr.dir/build.make tests/CMakeFiles/test-data-ptr.dir/build
.PHONY : test-data-ptr/fast

#=============================================================================
# Target rules for targets named tests

# Build rule for target.
tests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tests
.PHONY : tests

# fast build rule for target.
tests/fast:
	$(MAKE) -f tests/CMakeFiles/tests.dir/build.make tests/CMakeFiles/tests.dir/build
.PHONY : tests/fast

src/coding/huffman.o: src/coding/huffman.c.o

.PHONY : src/coding/huffman.o

# target to build an object file
src/coding/huffman.c.o:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/coding/huffman.c.o
.PHONY : src/coding/huffman.c.o

src/coding/huffman.i: src/coding/huffman.c.i

.PHONY : src/coding/huffman.i

# target to preprocess a source file
src/coding/huffman.c.i:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/coding/huffman.c.i
.PHONY : src/coding/huffman.c.i

src/coding/huffman.s: src/coding/huffman.c.s

.PHONY : src/coding/huffman.s

# target to generate assembly for a file
src/coding/huffman.c.s:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/coding/huffman.c.s
.PHONY : src/coding/huffman.c.s

src/core/alloc/alloc.o: src/core/alloc/alloc.c.o

.PHONY : src/core/alloc/alloc.o

# target to build an object file
src/core/alloc/alloc.c.o:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/core/alloc/alloc.c.o
.PHONY : src/core/alloc/alloc.c.o

src/core/alloc/alloc.i: src/core/alloc/alloc.c.i

.PHONY : src/core/alloc/alloc.i

# target to preprocess a source file
src/core/alloc/alloc.c.i:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/core/alloc/alloc.c.i
.PHONY : src/core/alloc/alloc.c.i

src/core/alloc/alloc.s: src/core/alloc/alloc.c.s

.PHONY : src/core/alloc/alloc.s

# target to generate assembly for a file
src/core/alloc/alloc.c.s:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/core/alloc/alloc.c.s
.PHONY : src/core/alloc/alloc.c.s

src/core/alloc/trace.o: src/core/alloc/trace.c.o

.PHONY : src/core/alloc/trace.o

# target to build an object file
src/core/alloc/trace.c.o:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/core/alloc/trace.c.o
.PHONY : src/core/alloc/trace.c.o

src/core/alloc/trace.i: src/core/alloc/trace.c.i

.PHONY : src/core/alloc/trace.i

# target to preprocess a source file
src/core/alloc/trace.c.i:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/core/alloc/trace.c.i
.PHONY : src/core/alloc/trace.c.i

src/core/alloc/trace.s: src/core/alloc/trace.c.s

.PHONY : src/core/alloc/trace.s

# target to generate assembly for a file
src/core/alloc/trace.c.s:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/core/alloc/trace.c.s
.PHONY : src/core/alloc/trace.c.s

src/core/async/parallel.o: src/core/async/parallel.c.o

.PHONY : src/core/async/parallel.o

# target to build an object file
src/core/async/parallel.c.o:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/core/async/parallel.c.o
.PHONY : src/core/async/parallel.c.o

src/core/async/parallel.i: src/core/async/parallel.c.i

.PHONY : src/core/async/parallel.i

# target to preprocess a source file
src/core/async/parallel.c.i:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/core/async/parallel.c.i
.PHONY : src/core/async/parallel.c.i

src/core/async/parallel.s: src/core/async/parallel.c.s

.PHONY : src/core/async/parallel.s

# target to generate assembly for a file
src/core/async/parallel.c.s:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/core/async/parallel.c.s
.PHONY : src/core/async/parallel.c.s

src/core/async/spin.o: src/core/async/spin.c.o

.PHONY : src/core/async/spin.o

# target to build an object file
src/core/async/spin.c.o:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/core/async/spin.c.o
.PHONY : src/core/async/spin.c.o

src/core/async/spin.i: src/core/async/spin.c.i

.PHONY : src/core/async/spin.i

# target to preprocess a source file
src/core/async/spin.c.i:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/core/async/spin.c.i
.PHONY : src/core/async/spin.c.i

src/core/async/spin.s: src/core/async/spin.c.s

.PHONY : src/core/async/spin.s

# target to generate assembly for a file
src/core/async/spin.c.s:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/core/async/spin.c.s
.PHONY : src/core/async/spin.c.s

src/core/carbon/archive.o: src/core/carbon/archive.c.o

.PHONY : src/core/carbon/archive.o

# target to build an object file
src/core/carbon/archive.c.o:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/core/carbon/archive.c.o
.PHONY : src/core/carbon/archive.c.o

src/core/carbon/archive.i: src/core/carbon/archive.c.i

.PHONY : src/core/carbon/archive.i

# target to preprocess a source file
src/core/carbon/archive.c.i:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/core/carbon/archive.c.i
.PHONY : src/core/carbon/archive.c.i

src/core/carbon/archive.s: src/core/carbon/archive.c.s

.PHONY : src/core/carbon/archive.s

# target to generate assembly for a file
src/core/carbon/archive.c.s:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/core/carbon/archive.c.s
.PHONY : src/core/carbon/archive.c.s

src/core/carbon/archive_converter.o: src/core/carbon/archive_converter.c.o

.PHONY : src/core/carbon/archive_converter.o

# target to build an object file
src/core/carbon/archive_converter.c.o:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/core/carbon/archive_converter.c.o
.PHONY : src/core/carbon/archive_converter.c.o

src/core/carbon/archive_converter.i: src/core/carbon/archive_converter.c.i

.PHONY : src/core/carbon/archive_converter.i

# target to preprocess a source file
src/core/carbon/archive_converter.c.i:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/core/carbon/archive_converter.c.i
.PHONY : src/core/carbon/archive_converter.c.i

src/core/carbon/archive_converter.s: src/core/carbon/archive_converter.c.s

.PHONY : src/core/carbon/archive_converter.s

# target to generate assembly for a file
src/core/carbon/archive_converter.c.s:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/core/carbon/archive_converter.c.s
.PHONY : src/core/carbon/archive_converter.c.s

src/core/carbon/archive_int.o: src/core/carbon/archive_int.c.o

.PHONY : src/core/carbon/archive_int.o

# target to build an object file
src/core/carbon/archive_int.c.o:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/core/carbon/archive_int.c.o
.PHONY : src/core/carbon/archive_int.c.o

src/core/carbon/archive_int.i: src/core/carbon/archive_int.c.i

.PHONY : src/core/carbon/archive_int.i

# target to preprocess a source file
src/core/carbon/archive_int.c.i:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/core/carbon/archive_int.c.i
.PHONY : src/core/carbon/archive_int.c.i

src/core/carbon/archive_int.s: src/core/carbon/archive_int.c.s

.PHONY : src/core/carbon/archive_int.s

# target to generate assembly for a file
src/core/carbon/archive_int.c.s:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/core/carbon/archive_int.c.s
.PHONY : src/core/carbon/archive_int.c.s

src/core/carbon/archive_io.o: src/core/carbon/archive_io.c.o

.PHONY : src/core/carbon/archive_io.o

# target to build an object file
src/core/carbon/archive_io.c.o:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/core/carbon/archive_io.c.o
.PHONY : src/core/carbon/archive_io.c.o

src/core/carbon/archive_io.i: src/core/carbon/archive_io.c.i

.PHONY : src/core/carbon/archive_io.i

# target to preprocess a source file
src/core/carbon/archive_io.c.i:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/core/carbon/archive_io.c.i
.PHONY : src/core/carbon/archive_io.c.i

src/core/carbon/archive_io.s: src/core/carbon/archive_io.c.s

.PHONY : src/core/carbon/archive_io.s

# target to generate assembly for a file
src/core/carbon/archive_io.c.s:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/core/carbon/archive_io.c.s
.PHONY : src/core/carbon/archive_io.c.s

src/core/carbon/archive_iter.o: src/core/carbon/archive_iter.c.o

.PHONY : src/core/carbon/archive_iter.o

# target to build an object file
src/core/carbon/archive_iter.c.o:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/core/carbon/archive_iter.c.o
.PHONY : src/core/carbon/archive_iter.c.o

src/core/carbon/archive_iter.i: src/core/carbon/archive_iter.c.i

.PHONY : src/core/carbon/archive_iter.i

# target to preprocess a source file
src/core/carbon/archive_iter.c.i:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/core/carbon/archive_iter.c.i
.PHONY : src/core/carbon/archive_iter.c.i

src/core/carbon/archive_iter.s: src/core/carbon/archive_iter.c.s

.PHONY : src/core/carbon/archive_iter.s

# target to generate assembly for a file
src/core/carbon/archive_iter.c.s:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/core/carbon/archive_iter.c.s
.PHONY : src/core/carbon/archive_iter.c.s

src/core/carbon/archive_query.o: src/core/carbon/archive_query.c.o

.PHONY : src/core/carbon/archive_query.o

# target to build an object file
src/core/carbon/archive_query.c.o:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/core/carbon/archive_query.c.o
.PHONY : src/core/carbon/archive_query.c.o

src/core/carbon/archive_query.i: src/core/carbon/archive_query.c.i

.PHONY : src/core/carbon/archive_query.i

# target to preprocess a source file
src/core/carbon/archive_query.c.i:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/core/carbon/archive_query.c.i
.PHONY : src/core/carbon/archive_query.c.i

src/core/carbon/archive_query.s: src/core/carbon/archive_query.c.s

.PHONY : src/core/carbon/archive_query.s

# target to generate assembly for a file
src/core/carbon/archive_query.c.s:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/core/carbon/archive_query.c.s
.PHONY : src/core/carbon/archive_query.c.s

src/core/carbon/archive_sid_cache.o: src/core/carbon/archive_sid_cache.c.o

.PHONY : src/core/carbon/archive_sid_cache.o

# target to build an object file
src/core/carbon/archive_sid_cache.c.o:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/core/carbon/archive_sid_cache.c.o
.PHONY : src/core/carbon/archive_sid_cache.c.o

src/core/carbon/archive_sid_cache.i: src/core/carbon/archive_sid_cache.c.i

.PHONY : src/core/carbon/archive_sid_cache.i

# target to preprocess a source file
src/core/carbon/archive_sid_cache.c.i:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/core/carbon/archive_sid_cache.c.i
.PHONY : src/core/carbon/archive_sid_cache.c.i

src/core/carbon/archive_sid_cache.s: src/core/carbon/archive_sid_cache.c.s

.PHONY : src/core/carbon/archive_sid_cache.s

# target to generate assembly for a file
src/core/carbon/archive_sid_cache.c.s:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/core/carbon/archive_sid_cache.c.s
.PHONY : src/core/carbon/archive_sid_cache.c.s

src/core/carbon/archive_strid_iter.o: src/core/carbon/archive_strid_iter.c.o

.PHONY : src/core/carbon/archive_strid_iter.o

# target to build an object file
src/core/carbon/archive_strid_iter.c.o:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/core/carbon/archive_strid_iter.c.o
.PHONY : src/core/carbon/archive_strid_iter.c.o

src/core/carbon/archive_strid_iter.i: src/core/carbon/archive_strid_iter.c.i

.PHONY : src/core/carbon/archive_strid_iter.i

# target to preprocess a source file
src/core/carbon/archive_strid_iter.c.i:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/core/carbon/archive_strid_iter.c.i
.PHONY : src/core/carbon/archive_strid_iter.c.i

src/core/carbon/archive_strid_iter.s: src/core/carbon/archive_strid_iter.c.s

.PHONY : src/core/carbon/archive_strid_iter.s

# target to generate assembly for a file
src/core/carbon/archive_strid_iter.c.s:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/core/carbon/archive_strid_iter.c.s
.PHONY : src/core/carbon/archive_strid_iter.c.s

src/core/carbon/archive_visitor.o: src/core/carbon/archive_visitor.c.o

.PHONY : src/core/carbon/archive_visitor.o

# target to build an object file
src/core/carbon/archive_visitor.c.o:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/core/carbon/archive_visitor.c.o
.PHONY : src/core/carbon/archive_visitor.c.o

src/core/carbon/archive_visitor.i: src/core/carbon/archive_visitor.c.i

.PHONY : src/core/carbon/archive_visitor.i

# target to preprocess a source file
src/core/carbon/archive_visitor.c.i:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/core/carbon/archive_visitor.c.i
.PHONY : src/core/carbon/archive_visitor.c.i

src/core/carbon/archive_visitor.s: src/core/carbon/archive_visitor.c.s

.PHONY : src/core/carbon/archive_visitor.s

# target to generate assembly for a file
src/core/carbon/archive_visitor.c.s:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/core/carbon/archive_visitor.c.s
.PHONY : src/core/carbon/archive_visitor.c.s

src/core/encode/encode_async.o: src/core/encode/encode_async.c.o

.PHONY : src/core/encode/encode_async.o

# target to build an object file
src/core/encode/encode_async.c.o:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/core/encode/encode_async.c.o
.PHONY : src/core/encode/encode_async.c.o

src/core/encode/encode_async.i: src/core/encode/encode_async.c.i

.PHONY : src/core/encode/encode_async.i

# target to preprocess a source file
src/core/encode/encode_async.c.i:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/core/encode/encode_async.c.i
.PHONY : src/core/encode/encode_async.c.i

src/core/encode/encode_async.s: src/core/encode/encode_async.c.s

.PHONY : src/core/encode/encode_async.s

# target to generate assembly for a file
src/core/encode/encode_async.c.s:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/core/encode/encode_async.c.s
.PHONY : src/core/encode/encode_async.c.s

src/core/encode/encode_sync.o: src/core/encode/encode_sync.c.o

.PHONY : src/core/encode/encode_sync.o

# target to build an object file
src/core/encode/encode_sync.c.o:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/core/encode/encode_sync.c.o
.PHONY : src/core/encode/encode_sync.c.o

src/core/encode/encode_sync.i: src/core/encode/encode_sync.c.i

.PHONY : src/core/encode/encode_sync.i

# target to preprocess a source file
src/core/encode/encode_sync.c.i:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/core/encode/encode_sync.c.i
.PHONY : src/core/encode/encode_sync.c.i

src/core/encode/encode_sync.s: src/core/encode/encode_sync.c.s

.PHONY : src/core/encode/encode_sync.s

# target to generate assembly for a file
src/core/encode/encode_sync.c.s:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/core/encode/encode_sync.c.s
.PHONY : src/core/encode/encode_sync.c.s

src/core/mem/block.o: src/core/mem/block.c.o

.PHONY : src/core/mem/block.o

# target to build an object file
src/core/mem/block.c.o:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/core/mem/block.c.o
.PHONY : src/core/mem/block.c.o

src/core/mem/block.i: src/core/mem/block.c.i

.PHONY : src/core/mem/block.i

# target to preprocess a source file
src/core/mem/block.c.i:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/core/mem/block.c.i
.PHONY : src/core/mem/block.c.i

src/core/mem/block.s: src/core/mem/block.c.s

.PHONY : src/core/mem/block.s

# target to generate assembly for a file
src/core/mem/block.c.s:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/core/mem/block.c.s
.PHONY : src/core/mem/block.c.s

src/core/mem/file.o: src/core/mem/file.c.o

.PHONY : src/core/mem/file.o

# target to build an object file
src/core/mem/file.c.o:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/core/mem/file.c.o
.PHONY : src/core/mem/file.c.o

src/core/mem/file.i: src/core/mem/file.c.i

.PHONY : src/core/mem/file.i

# target to preprocess a source file
src/core/mem/file.c.i:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/core/mem/file.c.i
.PHONY : src/core/mem/file.c.i

src/core/mem/file.s: src/core/mem/file.c.s

.PHONY : src/core/mem/file.s

# target to generate assembly for a file
src/core/mem/file.c.s:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/core/mem/file.c.s
.PHONY : src/core/mem/file.c.s

src/core/mem/pool.o: src/core/mem/pool.c.o

.PHONY : src/core/mem/pool.o

# target to build an object file
src/core/mem/pool.c.o:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/core/mem/pool.c.o
.PHONY : src/core/mem/pool.c.o

src/core/mem/pool.i: src/core/mem/pool.c.i

.PHONY : src/core/mem/pool.i

# target to preprocess a source file
src/core/mem/pool.c.i:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/core/mem/pool.c.i
.PHONY : src/core/mem/pool.c.i

src/core/mem/pool.s: src/core/mem/pool.c.s

.PHONY : src/core/mem/pool.s

# target to generate assembly for a file
src/core/mem/pool.c.s:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/core/mem/pool.c.s
.PHONY : src/core/mem/pool.c.s

src/core/mem/pools/magic.o: src/core/mem/pools/magic.c.o

.PHONY : src/core/mem/pools/magic.o

# target to build an object file
src/core/mem/pools/magic.c.o:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/core/mem/pools/magic.c.o
.PHONY : src/core/mem/pools/magic.c.o

src/core/mem/pools/magic.i: src/core/mem/pools/magic.c.i

.PHONY : src/core/mem/pools/magic.i

# target to preprocess a source file
src/core/mem/pools/magic.c.i:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/core/mem/pools/magic.c.i
.PHONY : src/core/mem/pools/magic.c.i

src/core/mem/pools/magic.s: src/core/mem/pools/magic.c.s

.PHONY : src/core/mem/pools/magic.s

# target to generate assembly for a file
src/core/mem/pools/magic.c.s:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/core/mem/pools/magic.c.s
.PHONY : src/core/mem/pools/magic.c.s

src/core/mem/pools/none.o: src/core/mem/pools/none.c.o

.PHONY : src/core/mem/pools/none.o

# target to build an object file
src/core/mem/pools/none.c.o:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/core/mem/pools/none.c.o
.PHONY : src/core/mem/pools/none.c.o

src/core/mem/pools/none.i: src/core/mem/pools/none.c.i

.PHONY : src/core/mem/pools/none.i

# target to preprocess a source file
src/core/mem/pools/none.c.i:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/core/mem/pools/none.c.i
.PHONY : src/core/mem/pools/none.c.i

src/core/mem/pools/none.s: src/core/mem/pools/none.c.s

.PHONY : src/core/mem/pools/none.s

# target to generate assembly for a file
src/core/mem/pools/none.c.s:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/core/mem/pools/none.c.s
.PHONY : src/core/mem/pools/none.c.s

src/core/oid/oid.o: src/core/oid/oid.c.o

.PHONY : src/core/oid/oid.o

# target to build an object file
src/core/oid/oid.c.o:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/core/oid/oid.c.o
.PHONY : src/core/oid/oid.c.o

src/core/oid/oid.i: src/core/oid/oid.c.i

.PHONY : src/core/oid/oid.i

# target to preprocess a source file
src/core/oid/oid.c.i:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/core/oid/oid.c.i
.PHONY : src/core/oid/oid.c.i

src/core/oid/oid.s: src/core/oid/oid.c.s

.PHONY : src/core/oid/oid.s

# target to generate assembly for a file
src/core/oid/oid.c.s:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/core/oid/oid.c.s
.PHONY : src/core/oid/oid.c.s

src/core/pack/coding_huffman.o: src/core/pack/coding_huffman.c.o

.PHONY : src/core/pack/coding_huffman.o

# target to build an object file
src/core/pack/coding_huffman.c.o:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/core/pack/coding_huffman.c.o
.PHONY : src/core/pack/coding_huffman.c.o

src/core/pack/coding_huffman.i: src/core/pack/coding_huffman.c.i

.PHONY : src/core/pack/coding_huffman.i

# target to preprocess a source file
src/core/pack/coding_huffman.c.i:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/core/pack/coding_huffman.c.i
.PHONY : src/core/pack/coding_huffman.c.i

src/core/pack/coding_huffman.s: src/core/pack/coding_huffman.c.s

.PHONY : src/core/pack/coding_huffman.s

# target to generate assembly for a file
src/core/pack/coding_huffman.c.s:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/core/pack/coding_huffman.c.s
.PHONY : src/core/pack/coding_huffman.c.s

src/core/pack/pack.o: src/core/pack/pack.c.o

.PHONY : src/core/pack/pack.o

# target to build an object file
src/core/pack/pack.c.o:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/core/pack/pack.c.o
.PHONY : src/core/pack/pack.c.o

src/core/pack/pack.i: src/core/pack/pack.c.i

.PHONY : src/core/pack/pack.i

# target to preprocess a source file
src/core/pack/pack.c.i:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/core/pack/pack.c.i
.PHONY : src/core/pack/pack.c.i

src/core/pack/pack.s: src/core/pack/pack.c.s

.PHONY : src/core/pack/pack.s

# target to generate assembly for a file
src/core/pack/pack.c.s:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/core/pack/pack.c.s
.PHONY : src/core/pack/pack.c.s

src/core/pack/pack_none.o: src/core/pack/pack_none.c.o

.PHONY : src/core/pack/pack_none.o

# target to build an object file
src/core/pack/pack_none.c.o:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/core/pack/pack_none.c.o
.PHONY : src/core/pack/pack_none.c.o

src/core/pack/pack_none.i: src/core/pack/pack_none.c.i

.PHONY : src/core/pack/pack_none.i

# target to preprocess a source file
src/core/pack/pack_none.c.i:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/core/pack/pack_none.c.i
.PHONY : src/core/pack/pack_none.c.i

src/core/pack/pack_none.s: src/core/pack/pack_none.c.s

.PHONY : src/core/pack/pack_none.s

# target to generate assembly for a file
src/core/pack/pack_none.c.s:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/core/pack/pack_none.c.s
.PHONY : src/core/pack/pack_none.c.s

src/core/ptrs/data_ptr.o: src/core/ptrs/data_ptr.c.o

.PHONY : src/core/ptrs/data_ptr.o

# target to build an object file
src/core/ptrs/data_ptr.c.o:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/core/ptrs/data_ptr.c.o
.PHONY : src/core/ptrs/data_ptr.c.o

src/core/ptrs/data_ptr.i: src/core/ptrs/data_ptr.c.i

.PHONY : src/core/ptrs/data_ptr.i

# target to preprocess a source file
src/core/ptrs/data_ptr.c.i:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/core/ptrs/data_ptr.c.i
.PHONY : src/core/ptrs/data_ptr.c.i

src/core/ptrs/data_ptr.s: src/core/ptrs/data_ptr.c.s

.PHONY : src/core/ptrs/data_ptr.s

# target to generate assembly for a file
src/core/ptrs/data_ptr.c.s:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/core/ptrs/data_ptr.c.s
.PHONY : src/core/ptrs/data_ptr.c.s

src/core/ptrs/tagged_ptr.o: src/core/ptrs/tagged_ptr.c.o

.PHONY : src/core/ptrs/tagged_ptr.o

# target to build an object file
src/core/ptrs/tagged_ptr.c.o:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/core/ptrs/tagged_ptr.c.o
.PHONY : src/core/ptrs/tagged_ptr.c.o

src/core/ptrs/tagged_ptr.i: src/core/ptrs/tagged_ptr.c.i

.PHONY : src/core/ptrs/tagged_ptr.i

# target to preprocess a source file
src/core/ptrs/tagged_ptr.c.i:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/core/ptrs/tagged_ptr.c.i
.PHONY : src/core/ptrs/tagged_ptr.c.i

src/core/ptrs/tagged_ptr.s: src/core/ptrs/tagged_ptr.c.s

.PHONY : src/core/ptrs/tagged_ptr.s

# target to generate assembly for a file
src/core/ptrs/tagged_ptr.c.s:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/core/ptrs/tagged_ptr.c.s
.PHONY : src/core/ptrs/tagged_ptr.c.s

src/core/strhash/strhash_mem.o: src/core/strhash/strhash_mem.c.o

.PHONY : src/core/strhash/strhash_mem.o

# target to build an object file
src/core/strhash/strhash_mem.c.o:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/core/strhash/strhash_mem.c.o
.PHONY : src/core/strhash/strhash_mem.c.o

src/core/strhash/strhash_mem.i: src/core/strhash/strhash_mem.c.i

.PHONY : src/core/strhash/strhash_mem.i

# target to preprocess a source file
src/core/strhash/strhash_mem.c.i:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/core/strhash/strhash_mem.c.i
.PHONY : src/core/strhash/strhash_mem.c.i

src/core/strhash/strhash_mem.s: src/core/strhash/strhash_mem.c.s

.PHONY : src/core/strhash/strhash_mem.s

# target to generate assembly for a file
src/core/strhash/strhash_mem.c.s:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/core/strhash/strhash_mem.c.s
.PHONY : src/core/strhash/strhash_mem.c.s

src/json/columndoc.o: src/json/columndoc.c.o

.PHONY : src/json/columndoc.o

# target to build an object file
src/json/columndoc.c.o:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/json/columndoc.c.o
.PHONY : src/json/columndoc.c.o

src/json/columndoc.i: src/json/columndoc.c.i

.PHONY : src/json/columndoc.i

# target to preprocess a source file
src/json/columndoc.c.i:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/json/columndoc.c.i
.PHONY : src/json/columndoc.c.i

src/json/columndoc.s: src/json/columndoc.c.s

.PHONY : src/json/columndoc.s

# target to generate assembly for a file
src/json/columndoc.c.s:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/json/columndoc.c.s
.PHONY : src/json/columndoc.c.s

src/json/doc.o: src/json/doc.c.o

.PHONY : src/json/doc.o

# target to build an object file
src/json/doc.c.o:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/json/doc.c.o
.PHONY : src/json/doc.c.o

src/json/doc.i: src/json/doc.c.i

.PHONY : src/json/doc.i

# target to preprocess a source file
src/json/doc.c.i:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/json/doc.c.i
.PHONY : src/json/doc.c.i

src/json/doc.s: src/json/doc.c.s

.PHONY : src/json/doc.s

# target to generate assembly for a file
src/json/doc.c.s:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/json/doc.c.s
.PHONY : src/json/doc.c.s

src/json/encoded_doc.o: src/json/encoded_doc.c.o

.PHONY : src/json/encoded_doc.o

# target to build an object file
src/json/encoded_doc.c.o:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/json/encoded_doc.c.o
.PHONY : src/json/encoded_doc.c.o

src/json/encoded_doc.i: src/json/encoded_doc.c.i

.PHONY : src/json/encoded_doc.i

# target to preprocess a source file
src/json/encoded_doc.c.i:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/json/encoded_doc.c.i
.PHONY : src/json/encoded_doc.c.i

src/json/encoded_doc.s: src/json/encoded_doc.c.s

.PHONY : src/json/encoded_doc.s

# target to generate assembly for a file
src/json/encoded_doc.c.s:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/json/encoded_doc.c.s
.PHONY : src/json/encoded_doc.c.s

src/json/json.o: src/json/json.c.o

.PHONY : src/json/json.o

# target to build an object file
src/json/json.c.o:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/json/json.c.o
.PHONY : src/json/json.c.o

src/json/json.i: src/json/json.c.i

.PHONY : src/json/json.i

# target to preprocess a source file
src/json/json.c.i:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/json/json.c.i
.PHONY : src/json/json.c.i

src/json/json.s: src/json/json.c.s

.PHONY : src/json/json.s

# target to generate assembly for a file
src/json/json.c.s:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/json/json.c.s
.PHONY : src/json/json.c.s

src/shared/error.o: src/shared/error.c.o

.PHONY : src/shared/error.o

# target to build an object file
src/shared/error.c.o:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/shared/error.c.o
.PHONY : src/shared/error.c.o

src/shared/error.i: src/shared/error.c.i

.PHONY : src/shared/error.i

# target to preprocess a source file
src/shared/error.c.i:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/shared/error.c.i
.PHONY : src/shared/error.c.i

src/shared/error.s: src/shared/error.c.s

.PHONY : src/shared/error.s

# target to generate assembly for a file
src/shared/error.c.s:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/shared/error.c.s
.PHONY : src/shared/error.c.s

src/shell/opt.o: src/shell/opt.c.o

.PHONY : src/shell/opt.o

# target to build an object file
src/shell/opt.c.o:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/shell/opt.c.o
.PHONY : src/shell/opt.c.o

src/shell/opt.i: src/shell/opt.c.i

.PHONY : src/shell/opt.i

# target to preprocess a source file
src/shell/opt.c.i:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/shell/opt.c.i
.PHONY : src/shell/opt.c.i

src/shell/opt.s: src/shell/opt.c.s

.PHONY : src/shell/opt.s

# target to generate assembly for a file
src/shell/opt.c.s:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/shell/opt.c.s
.PHONY : src/shell/opt.c.s

src/std/bitmap.o: src/std/bitmap.c.o

.PHONY : src/std/bitmap.o

# target to build an object file
src/std/bitmap.c.o:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/std/bitmap.c.o
.PHONY : src/std/bitmap.c.o

src/std/bitmap.i: src/std/bitmap.c.i

.PHONY : src/std/bitmap.i

# target to preprocess a source file
src/std/bitmap.c.i:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/std/bitmap.c.i
.PHONY : src/std/bitmap.c.i

src/std/bitmap.s: src/std/bitmap.c.s

.PHONY : src/std/bitmap.s

# target to generate assembly for a file
src/std/bitmap.c.s:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/std/bitmap.c.s
.PHONY : src/std/bitmap.c.s

src/std/bloom.o: src/std/bloom.c.o

.PHONY : src/std/bloom.o

# target to build an object file
src/std/bloom.c.o:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/std/bloom.c.o
.PHONY : src/std/bloom.c.o

src/std/bloom.i: src/std/bloom.c.i

.PHONY : src/std/bloom.i

# target to preprocess a source file
src/std/bloom.c.i:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/std/bloom.c.i
.PHONY : src/std/bloom.c.i

src/std/bloom.s: src/std/bloom.c.s

.PHONY : src/std/bloom.s

# target to generate assembly for a file
src/std/bloom.c.s:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/std/bloom.c.s
.PHONY : src/std/bloom.c.s

src/std/hash_set.o: src/std/hash_set.c.o

.PHONY : src/std/hash_set.o

# target to build an object file
src/std/hash_set.c.o:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/std/hash_set.c.o
.PHONY : src/std/hash_set.c.o

src/std/hash_set.i: src/std/hash_set.c.i

.PHONY : src/std/hash_set.i

# target to preprocess a source file
src/std/hash_set.c.i:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/std/hash_set.c.i
.PHONY : src/std/hash_set.c.i

src/std/hash_set.s: src/std/hash_set.c.s

.PHONY : src/std/hash_set.s

# target to generate assembly for a file
src/std/hash_set.c.s:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/std/hash_set.c.s
.PHONY : src/std/hash_set.c.s

src/std/hash_table.o: src/std/hash_table.c.o

.PHONY : src/std/hash_table.o

# target to build an object file
src/std/hash_table.c.o:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/std/hash_table.c.o
.PHONY : src/std/hash_table.c.o

src/std/hash_table.i: src/std/hash_table.c.i

.PHONY : src/std/hash_table.i

# target to preprocess a source file
src/std/hash_table.c.i:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/std/hash_table.c.i
.PHONY : src/std/hash_table.c.i

src/std/hash_table.s: src/std/hash_table.c.s

.PHONY : src/std/hash_table.s

# target to generate assembly for a file
src/std/hash_table.c.s:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/std/hash_table.c.s
.PHONY : src/std/hash_table.c.s

src/std/histogram.o: src/std/histogram.c.o

.PHONY : src/std/histogram.o

# target to build an object file
src/std/histogram.c.o:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/std/histogram.c.o
.PHONY : src/std/histogram.c.o

src/std/histogram.i: src/std/histogram.c.i

.PHONY : src/std/histogram.i

# target to preprocess a source file
src/std/histogram.c.i:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/std/histogram.c.i
.PHONY : src/std/histogram.c.i

src/std/histogram.s: src/std/histogram.c.s

.PHONY : src/std/histogram.s

# target to generate assembly for a file
src/std/histogram.c.s:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/std/histogram.c.s
.PHONY : src/std/histogram.c.s

src/std/sort.o: src/std/sort.c.o

.PHONY : src/std/sort.o

# target to build an object file
src/std/sort.c.o:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/std/sort.c.o
.PHONY : src/std/sort.c.o

src/std/sort.i: src/std/sort.c.i

.PHONY : src/std/sort.i

# target to preprocess a source file
src/std/sort.c.i:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/std/sort.c.i
.PHONY : src/std/sort.c.i

src/std/sort.s: src/std/sort.c.s

.PHONY : src/std/sort.s

# target to generate assembly for a file
src/std/sort.c.s:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/std/sort.c.s
.PHONY : src/std/sort.c.s

src/std/vec.o: src/std/vec.c.o

.PHONY : src/std/vec.o

# target to build an object file
src/std/vec.c.o:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/std/vec.c.o
.PHONY : src/std/vec.c.o

src/std/vec.i: src/std/vec.c.i

.PHONY : src/std/vec.i

# target to preprocess a source file
src/std/vec.c.i:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/std/vec.c.i
.PHONY : src/std/vec.c.i

src/std/vec.s: src/std/vec.c.s

.PHONY : src/std/vec.s

# target to generate assembly for a file
src/std/vec.c.s:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/std/vec.c.s
.PHONY : src/std/vec.c.s

src/stdx/slicelist.o: src/stdx/slicelist.c.o

.PHONY : src/stdx/slicelist.o

# target to build an object file
src/stdx/slicelist.c.o:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/stdx/slicelist.c.o
.PHONY : src/stdx/slicelist.c.o

src/stdx/slicelist.i: src/stdx/slicelist.c.i

.PHONY : src/stdx/slicelist.i

# target to preprocess a source file
src/stdx/slicelist.c.i:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/stdx/slicelist.c.i
.PHONY : src/stdx/slicelist.c.i

src/stdx/slicelist.s: src/stdx/slicelist.c.s

.PHONY : src/stdx/slicelist.s

# target to generate assembly for a file
src/stdx/slicelist.c.s:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/stdx/slicelist.c.s
.PHONY : src/stdx/slicelist.c.s

src/utils/convert.o: src/utils/convert.c.o

.PHONY : src/utils/convert.o

# target to build an object file
src/utils/convert.c.o:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/utils/convert.c.o
.PHONY : src/utils/convert.c.o

src/utils/convert.i: src/utils/convert.c.i

.PHONY : src/utils/convert.i

# target to preprocess a source file
src/utils/convert.c.i:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/utils/convert.c.i
.PHONY : src/utils/convert.c.i

src/utils/convert.s: src/utils/convert.c.s

.PHONY : src/utils/convert.s

# target to generate assembly for a file
src/utils/convert.c.s:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/utils/convert.c.s
.PHONY : src/utils/convert.c.s

src/utils/time.o: src/utils/time.c.o

.PHONY : src/utils/time.o

# target to build an object file
src/utils/time.c.o:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/utils/time.c.o
.PHONY : src/utils/time.c.o

src/utils/time.i: src/utils/time.c.i

.PHONY : src/utils/time.i

# target to preprocess a source file
src/utils/time.c.i:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/utils/time.c.i
.PHONY : src/utils/time.c.i

src/utils/time.s: src/utils/time.c.s

.PHONY : src/utils/time.s

# target to generate assembly for a file
src/utils/time.c.s:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/utils/time.c.s
.PHONY : src/utils/time.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... install/local"
	@echo "... test"
	@echo "... list_install_components"
	@echo "... carbon"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... carbon-tool"
	@echo "... benches"
	@echo "... bench-mem-pools"
	@echo "... examples-error"
	@echo "... test-histogram"
	@echo "... test-archive-converter"
	@echo "... test-object-ids"
	@echo "... test-fix-map"
	@echo "... test-archive-ops"
	@echo "... test-archive-iter"
	@echo "... test-mempools"
	@echo "... test-tagged-ptr"
	@echo "... test-data-ptr"
	@echo "... tests"
	@echo "... src/coding/huffman.o"
	@echo "... src/coding/huffman.i"
	@echo "... src/coding/huffman.s"
	@echo "... src/core/alloc/alloc.o"
	@echo "... src/core/alloc/alloc.i"
	@echo "... src/core/alloc/alloc.s"
	@echo "... src/core/alloc/trace.o"
	@echo "... src/core/alloc/trace.i"
	@echo "... src/core/alloc/trace.s"
	@echo "... src/core/async/parallel.o"
	@echo "... src/core/async/parallel.i"
	@echo "... src/core/async/parallel.s"
	@echo "... src/core/async/spin.o"
	@echo "... src/core/async/spin.i"
	@echo "... src/core/async/spin.s"
	@echo "... src/core/carbon/archive.o"
	@echo "... src/core/carbon/archive.i"
	@echo "... src/core/carbon/archive.s"
	@echo "... src/core/carbon/archive_converter.o"
	@echo "... src/core/carbon/archive_converter.i"
	@echo "... src/core/carbon/archive_converter.s"
	@echo "... src/core/carbon/archive_int.o"
	@echo "... src/core/carbon/archive_int.i"
	@echo "... src/core/carbon/archive_int.s"
	@echo "... src/core/carbon/archive_io.o"
	@echo "... src/core/carbon/archive_io.i"
	@echo "... src/core/carbon/archive_io.s"
	@echo "... src/core/carbon/archive_iter.o"
	@echo "... src/core/carbon/archive_iter.i"
	@echo "... src/core/carbon/archive_iter.s"
	@echo "... src/core/carbon/archive_query.o"
	@echo "... src/core/carbon/archive_query.i"
	@echo "... src/core/carbon/archive_query.s"
	@echo "... src/core/carbon/archive_sid_cache.o"
	@echo "... src/core/carbon/archive_sid_cache.i"
	@echo "... src/core/carbon/archive_sid_cache.s"
	@echo "... src/core/carbon/archive_strid_iter.o"
	@echo "... src/core/carbon/archive_strid_iter.i"
	@echo "... src/core/carbon/archive_strid_iter.s"
	@echo "... src/core/carbon/archive_visitor.o"
	@echo "... src/core/carbon/archive_visitor.i"
	@echo "... src/core/carbon/archive_visitor.s"
	@echo "... src/core/encode/encode_async.o"
	@echo "... src/core/encode/encode_async.i"
	@echo "... src/core/encode/encode_async.s"
	@echo "... src/core/encode/encode_sync.o"
	@echo "... src/core/encode/encode_sync.i"
	@echo "... src/core/encode/encode_sync.s"
	@echo "... src/core/mem/block.o"
	@echo "... src/core/mem/block.i"
	@echo "... src/core/mem/block.s"
	@echo "... src/core/mem/file.o"
	@echo "... src/core/mem/file.i"
	@echo "... src/core/mem/file.s"
	@echo "... src/core/mem/pool.o"
	@echo "... src/core/mem/pool.i"
	@echo "... src/core/mem/pool.s"
	@echo "... src/core/mem/pools/magic.o"
	@echo "... src/core/mem/pools/magic.i"
	@echo "... src/core/mem/pools/magic.s"
	@echo "... src/core/mem/pools/none.o"
	@echo "... src/core/mem/pools/none.i"
	@echo "... src/core/mem/pools/none.s"
	@echo "... src/core/oid/oid.o"
	@echo "... src/core/oid/oid.i"
	@echo "... src/core/oid/oid.s"
	@echo "... src/core/pack/coding_huffman.o"
	@echo "... src/core/pack/coding_huffman.i"
	@echo "... src/core/pack/coding_huffman.s"
	@echo "... src/core/pack/pack.o"
	@echo "... src/core/pack/pack.i"
	@echo "... src/core/pack/pack.s"
	@echo "... src/core/pack/pack_none.o"
	@echo "... src/core/pack/pack_none.i"
	@echo "... src/core/pack/pack_none.s"
	@echo "... src/core/ptrs/data_ptr.o"
	@echo "... src/core/ptrs/data_ptr.i"
	@echo "... src/core/ptrs/data_ptr.s"
	@echo "... src/core/ptrs/tagged_ptr.o"
	@echo "... src/core/ptrs/tagged_ptr.i"
	@echo "... src/core/ptrs/tagged_ptr.s"
	@echo "... src/core/strhash/strhash_mem.o"
	@echo "... src/core/strhash/strhash_mem.i"
	@echo "... src/core/strhash/strhash_mem.s"
	@echo "... src/json/columndoc.o"
	@echo "... src/json/columndoc.i"
	@echo "... src/json/columndoc.s"
	@echo "... src/json/doc.o"
	@echo "... src/json/doc.i"
	@echo "... src/json/doc.s"
	@echo "... src/json/encoded_doc.o"
	@echo "... src/json/encoded_doc.i"
	@echo "... src/json/encoded_doc.s"
	@echo "... src/json/json.o"
	@echo "... src/json/json.i"
	@echo "... src/json/json.s"
	@echo "... src/shared/error.o"
	@echo "... src/shared/error.i"
	@echo "... src/shared/error.s"
	@echo "... src/shell/opt.o"
	@echo "... src/shell/opt.i"
	@echo "... src/shell/opt.s"
	@echo "... src/std/bitmap.o"
	@echo "... src/std/bitmap.i"
	@echo "... src/std/bitmap.s"
	@echo "... src/std/bloom.o"
	@echo "... src/std/bloom.i"
	@echo "... src/std/bloom.s"
	@echo "... src/std/hash_set.o"
	@echo "... src/std/hash_set.i"
	@echo "... src/std/hash_set.s"
	@echo "... src/std/hash_table.o"
	@echo "... src/std/hash_table.i"
	@echo "... src/std/hash_table.s"
	@echo "... src/std/histogram.o"
	@echo "... src/std/histogram.i"
	@echo "... src/std/histogram.s"
	@echo "... src/std/sort.o"
	@echo "... src/std/sort.i"
	@echo "... src/std/sort.s"
	@echo "... src/std/vec.o"
	@echo "... src/std/vec.i"
	@echo "... src/std/vec.s"
	@echo "... src/stdx/slicelist.o"
	@echo "... src/stdx/slicelist.i"
	@echo "... src/stdx/slicelist.s"
	@echo "... src/utils/convert.o"
	@echo "... src/utils/convert.i"
	@echo "... src/utils/convert.s"
	@echo "... src/utils/time.o"
	@echo "... src/utils/time.i"
	@echo "... src/utils/time.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

